default: &default
  adapter: "postgresql"

development:
  <<: *default
  host: "localhost"
  username: "postgres"
  password: "postgres"
  database: "eb_test_development"

production:
  <<: *default
  host: <%= ENV["RDS_DB_HOST"] %>
  username: "postgres"
  password: "postgres"
  database: "eb_test_production"
